//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASR_Management_System.Pages.Update_Records_Pgs {
    
    
    public partial class ConfirmDeletions {
        
        /// <summary>
        /// cbDeleteAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbDeleteAll;
        
        /// <summary>
        /// MutuallyExclusiveCheckBoxExtender1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender MutuallyExclusiveCheckBoxExtender1;
        
        /// <summary>
        /// cbRestoreAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbRestoreAll;
        
        /// <summary>
        /// MutuallyExclusiveCheckBoxExtender3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender MutuallyExclusiveCheckBoxExtender3;
        
        /// <summary>
        /// rptrDeletedSubmissions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptrDeletedSubmissions;
        
        /// <summary>
        /// SubmissionDS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SubmissionDS;
    }
}
